### ISSUE TITLE
[request] renew script ?

### ISSUE THREAD

**Issue by ychaouche** [diafygi/letsencrypt-nosudo#73] opened 2016-06-01 13:40 UTC
Thanks for the script. Should we renew our certificates by running the script again or ?

**Comment by jbwhaley** [comment] 2016-07-06 21:29
Yes, please.

**Comment by anko** [comment] 2016-07-08 17:38
Duplicate of https://github.com/diafygi/letsencrypt-nosudo/issues/55?

**Comment by diafygi** [comment] 2018-03-13 14:57
Renewal can be done by just re-running `sign_csr.py` with the same CSR and public key files.

**Closed as completed by diafygi** 2018-03-13 14:57 UTC
