### ISSUE TITLE
'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by christiankirsch** [diafygi/letsencrypt-nosudo#16] opened 2015-11-07 23:12 UTC
Following the instructions with generating user key and pub as well as domain key and csr I got this error when invoking your script:

```
Reading pubkey file...
Traceback (most recent call last):
  File "sign_csr.py", line 429, in <module>
    signed_crt = sign_csr(args.public_key, args.csr_path, email=args.email)
  File "sign_csr.py", line 39, in sign_csr
    pub_hex, pub_exp = re.search("Modulus\:\s+00:([a-f0-9\:\s]+?)Exponent\: ([0-9]+)", out, re.MULTILINE|re.DOTALL).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

I am on Mac OS X 10.10.5 with Python 2.7.10. I tried re-generating user / domain keys several times... Any ideas?

**Comment by diafygi** [comment] 2015-11-08 00:31
Thanks, could you please post your user public key you are trying to use ?

**Comment by christiankirsch** [comment] 2015-11-08 12:50
sure:

```
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAtDO5zSgwbVKBFlNwoqUX
9Trt2nulgpopnJ7xk/OHtPwP6twL0TRx505oNStScG1aUpJh9AEQWlByz7SVuKKd
KUkO3X3ujnjO1J8TFRPrGVQN9dOOTLDLkF8lin84RW3J2xTAqG4Tv0Oa80b7fM26
Lsc2pKlBW7iJpTfy5qlNhv9VfmjMhKiFj9UwyUxNUDj1TxmUBwdSBgUzswYhSL+Q
OlE2GJklkoUnG9B1YPlqKSBgBEV9Md6DuHbSm9U/j17YMMYidgZgnoMqLUsX7+2/
hpFo9751HDgXZ/yrIB9F22ITewfqfJ4UnAwMCF6TLPJtiWijxP2APK7ZZCaLjs7K
a8qEb08L1ZL+MSE1sYbYbzBDmIrlF64M/omfeJZ43flE59lcBd2MftP4tJnGaesv
7ifcuJd1UWbhIBZOrwCINfpx2ZquTKRT1EqgDQPDHhs9Vu8SWO3TvbbQPu+aX8kK
tjg25NWyuvYO/dpJjbXvxidb2a/hIsQFw97BZ7D4DmBBBZh4+W4e0kOjPlpYMsYM
8CiMTkRIWGbeTCJJhQMLkpds0xL3m9LH6iI0YKm7Vf5NTKrxsUuD0BOsWbpW2C3M
8lrhB19xJXYpGDqAAD4wPULL3MlxECn5dk6x9xrdJCIlaLyVpR9NhqG533NU5V9Z
46aoEV9+u+Rv8bNqvLfrxPkCAwEAAQ==
-----END PUBLIC KEY-----
```

**Comment by billzhong** [comment] 2015-11-08 17:42
I confirmed same issue on OS X 10.11.1 with Python 2.7.10 and OpenSSL 0.9.8zg

**Comment by christiankirsch** [comment] 2015-11-08 19:43
I am also using OpenSSL 0.9.8zg.

**Comment by diafygi** [comment] 2015-11-08 19:52
@christiankirsch @billzhong It looks like the output of that version of OpenSSL is different from the Linux default. I pushed an updated regex that should work for both. Please verify?

**Comment by billzhong** [comment] 2015-11-08 20:38
@diafygi The updated regex works for me. Thanks.

**Comment by diafygi** [comment] 2015-11-12 05:30
Since @billzhong confirmed the fix, I'm closing this issue. @christiankirsch, please ask to reopen if it isn't fixed for you. Thanks!

**Closed as completed by diafygi** 2015-11-12 05:30 UTC

**Comment by jankkm** [comment] 2016-02-05 11:30
This should also be changed in revoke_crt.py in line 34.
